---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: agarwalkeshav670
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "agarwalkeshav670/calculators"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
        
    - name: Start Docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name calculators1 agarwalkeshav670/calculators
